website/events/urls.py
from django.urls import path

from events.views import (
    EventListView,
    EventDetailView,
    EventRegisterView,
    EventUnregisterView,
    EventFormView,
    EventICSView,
)

urlpatterns = [
    path("", EventListView.as_view(), name="list"),
    path("events.ics", EventICSView.as_view(), name="ics"),
    path("<int:pk>/", EventDetailView.as_view(), name="detail"),
    path("<int:pk>/register/", EventRegisterView.as_view(), name="register"),
    path("<int:pk>/form", EventFormView.as_view(), name="form"),
    path("<int:pk>/unregister/", EventUnregisterView.as_view(), name="unregister"),
]

website/members/urls.py
from django.urls import path

from members.views import MemberListView, MemberDetailView, MemberEditView

urlpatterns = [
    path("", MemberListView.as_view(), name="list"),
    path("<int:pk>/", MemberDetailView.as_view(), name="detail"),
    path("edit/", MemberEditView.as_view(), name="edit"),
]

website/website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.defaults import page_not_found, server_error

from members.sitemaps import BecomeAMemberSitemap
from members.views import BecomeAMemberView, PasswordSetView


def custom_page_not_found(request):
    return page_not_found(request, None)


def custom_server_error(request):
    return server_error(request)


urlpatterns = (
    [
        path("i18n/", include("django.conf.urls.i18n")),
        path(
            "sitemap.xml",
            sitemap,
            {"sitemaps": {"cmspages": CMSSitemap, "member": BecomeAMemberSitemap}},
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

urlpatterns += i18n_patterns(
    path("404/", custom_page_not_found),
    path("500/", custom_server_error),
    path("admin/", admin.site.urls),
    path("user/", include("django.contrib.auth.urls")),
    path("become-a-member/", BecomeAMemberView.as_view(), name="become-a-member"),
    path(
        "activate-account/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="activate-account",
    ),
    re_path(r"^", include("cms.urls")),
)

website/members/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from filer.fields.file import FilerFileField
from django.contrib.auth.models import User


def user_directory_path(instance, filename):
    return "profile_pic/user_{0}/{1}".format(instance.user.id, filename)


class Member(models.Model):
    """A model to hold all extra personal information about members."""

    RU = "RU"
    HAN = "HAN"
    NOSTUDENT = "NS"
    TYPE_STUDENT = [
        (RU, _("Radboud University")),
        (HAN, _("HAN")),
        (NOSTUDENT, _("Not a student")),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    birthday = models.DateField(verbose_name=_("birth date"))

    MAN = "Man"
    WOMAN = "Woman"
    OTHER = "Other"
    UNSPECIFIED = "Unspecified"
    GENDER_CHOICES = [
        (MAN, _("man")),
        (WOMAN, _("woman")),
        (OTHER, _("other")),
        (UNSPECIFIED, _("unspecified")),
    ]

    gender = models.CharField(
        max_length=64, verbose_name=_("gender"), choices=GENDER_CHOICES
    )

    pronouns = models.CharField(
        blank=True,
        null=True,
        max_length=256,
        verbose_name=_("pronouns"),
        help_text=_("Please write this in english"),
    )

    phone_number = models.CharField(max_length=16, verbose_name=_("phone number"))

    street_address = models.CharField(
        max_length=255, verbose_name=_("street name and house number")
    )

    postcode = models.CharField(
        max_length=64,
        validators=[
            RegexValidator(
                regex="^[\\s\\da-zA-Z]+$",
                message=_("postcode can only contain spaces, digits and letters"),
                code="invalid_postcode",
            )
        ],
        verbose_name=_("zipcode"),
    )

    city = models.CharField(max_length=52, verbose_name=_("city"))

    student_type = models.CharField(
        max_length=3, choices=TYPE_STUDENT, verbose_name=_("Where do you study?")
    )

    sports_card_number = models.CharField(
        max_length=10,
        verbose_name=_("Sport center customer number"),
        validators=[
            RegexValidator(
                regex="^\\d{6}$",
                message=_("sports card number has invalid form"),
                code="invalid_sports_card_number",
            ),
        ],
    )

    other_club = models.BooleanField(verbose_name=_("other club"))

    preferred_language = models.CharField(
        choices=settings.LANGUAGES,
        default="nl",
        max_length=3,
        verbose_name=_("preferred language"),
    )

    google_email = models.EmailField(verbose_name=_("google email address"))

    remarks = models.TextField(blank=True, null=True, verbose_name=_("remarks"))

    bio = models.TextField(
        blank=True, null=True, verbose_name=_("bio"), max_length=1000
    )
    profile_picture = models.ImageField(
        blank=True, null=True, upload_to=user_directory_path
    )

    FIRST_NAME = "Firstname"
    FULL_NAME = "Fullname"
    INITIALS = "Initials"
    FULL_NAME_NICKNAME = "FullnameNickname"
    FIRST_NAME_NICKNAME = "FirstnameNickname"
    LAST_NAME_NICKNAME = "LastnameNickname"
    DISPLAY_NAME_CHOICES = [
        (FIRST_NAME, _("First name")),
        (FULL_NAME, _("Full name")),
        (INITIALS, _("Initial with last name")),
        (FULL_NAME_NICKNAME, _("Full name with nickname")),
        (FIRST_NAME_NICKNAME, _("First name with nickname")),
        (LAST_NAME_NICKNAME, _("Last name with nickname")),
    ]

    display_name = models.CharField(
        max_length=64,
        verbose_name=_("display name"),
        choices=DISPLAY_NAME_CHOICES,
        default=FIRST_NAME,
    )
    nickname = models.CharField(
        max_length=64, verbose_name=_("nickname"), blank=True, null=True
    )

    def clean(self) -> None:
        if self.birthday and self.birthday > timezone.now().date():
            raise ValidationError({"birthday": _("Your birthday must lay in the past")})

    def save(self, *args, **kwargs):
        self.sports_card_number = self.sports_card_number.lower()
        super().save(*args, **kwargs)

    class Meta:
        permissions = (("can_accept_or_reject", _("can accept or reject")),)

    def name(self) -> str:
        if self.display_name == self.FIRST_NAME:
            return self.user.first_name
        elif self.display_name == self.FULL_NAME:
            return self.user.get_full_name()
        elif self.display_name == self.INITIALS:
            return self.user.first_name[0] + " " + self.user.last_name
        elif self.display_name == self.FULL_NAME_NICKNAME:
            return f'{self.user.first_name} "{self.nickname}" {self.user.last_name}'
        elif self.display_name == self.FIRST_NAME_NICKNAME:
            return f'{self.user.first_name} "{self.nickname}"'
        elif self.display_name == self.LAST_NAME_NICKNAME:
            return f'"{self.nickname}" {self.user.last_name}'
        else:
            return ""

    def default_pronouns(self) -> str:
        if self.pronouns:
            return self.pronouns
        elif self.gender == self.MAN:
            return "(he/him)"
        elif self.gender == self.WOMAN:
            return "(she/her)"
        elif self.gender == self.OTHER:
            return "(they/them)"
        else:
            return ""

    def get_absolute_url(self):
        return reverse("members:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Member: {self.name()}"


class MemberSettings(models.Model):
    privacyFile = FilerFileField(null=True, blank=True, on_delete=models.CASCADE)  # type: ignore

    def save(self, *args, **kwargs):
        if MemberSettings.objects.exists():
            raise ValueError("This model already has its record.")
        else:
            super().save(*args, **kwargs)

    def __str__(self):
        return "Settings"


def get_name(self):
    return f"User: {self.first_name} {self.last_name}"


User.add_to_class("__str__", get_name)

website/members/views.py
import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetConfirmView
from django.views.generic import DetailView, ListView, UpdateView, FormView
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters

from members.forms import BecomeAMemberForm, ActivateAccountForm, EditMemberForm
from members.models import MemberSettings, Member
from members.tokens import default_activate_token_generator


class MemberListView(LoginRequiredMixin, ListView):
    model = Member
    paginate_by = 24

    def get_queryset(self):
        members = super().get_queryset()
        query = self.request.GET.get("q")
        members = members.filter(user__is_active=True).order_by("user__first_name")
        if query:
            return members.filter(user__first_name__icontains=query)
        return members

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["pages"] = range(1, context["page_obj"].paginator.num_pages + 1)
        return context


class MemberDetailView(LoginRequiredMixin, DetailView):
    model = Member

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            "committee_memberships"
        ] = self.object.user.committeemembership_set.order_by("since").all()
        context["board_memberships"] = self.object.boardmembership_set.order_by(
            "board__start"
        ).all()
        context["today"] = datetime.datetime.today()
        return context


class MemberEditView(LoginRequiredMixin, UpdateView):
    form_class = EditMemberForm

    def get_object(self, queryset=None):
        return self.request.user.member


class BecomeAMemberView(FormView):
    template_name = "members/become_a_member.html"
    form_class = BecomeAMemberForm
    success_url = "/"

    @method_decorator(sensitive_post_parameters("password"))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["privacyFile"] = MemberSettings.objects.first().privacyFile
        return context


class PasswordSetView(PasswordResetConfirmView):
    template_name = "members/passwerd_set.html"
    token_generator = default_activate_token_generator
    success_url = "/"
    form_class = ActivateAccountForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["privacyFile"] = MemberSettings.objects.first().privacyFile
        if self.user:
            context["user"] = self.user
        return context

website/members/templates/members/become_a_member.html
{% extends "page.html" %}
{% load i18n bootstrap5 sass_tags static %}

{% block title %}{% trans "Become a member" %}{% endblock title %}
{% block pagetitle %}{% trans "Become a member" %}{% endblock pagetitle %}

{% block content %}
    <form method="post" autocomplete="on">{% csrf_token %}
        <div class="row g-3 mb-5">
            {% if form.non_field_errors %}
                <div class="row mb-3">
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="col-lg">
                <div class="form-group reg_spacing">
                    <label for="{{ form.firstname.id_for_label }}" class="form-label">{{ form.firstname.label }}</label>
                    <input type="text" class="form-control {% if form.firstname.errors %}is-invalid{% endif %}"
                           name="{{ form.firstname.html_name }}" placeholder="{{ form.firstname.label }}" required>
                    {% if form.firstname.errors %}
                        <div class="invalid-feedback">
                            {{ form.firstname.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.lastname.id_for_label }}" class="form-label">{{ form.lastname.label }}</label>
                    <input type="text" class="form-control {% if form.lastname.errors %}is-invalid{% endif %}"
                           name="{{ form.lastname.html_name }}" placeholder="{{ form.lastname.label }}" required>
                    {% if form.lastname.errors %}
                        <div class="invalid-feedback">
                            {{ form.lastname.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.birthday.id_for_label }}" class="form-label">{{ form.birthday.label }}</label>
                    <input type="text" class="form-control {% if form.birthday.errors %}is-invalid{% endif %}"
                           name="{{ form.birthday.html_name }}" placeholder="{% trans "dd/mm/yyyy" %}" required>
                    {% if form.birthday.errors %}
                        <div class="invalid-feedback">
                            {{ form.birthday.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.gender.id_for_label }}" class="form-label">{{ form.gender.label }}</label>
                    <select class="form-select custom-select {% if form.gender.errors %}is-invalid{% endif %}"
                            name="{{ form.gender.html_name }}" id="gender" onchange="hideField()" required>
                        {% for choice in form.gender %}
                            {{ choice }}
                        {% endfor %}
                    </select>
                    {% if form.gender.errors %}
                        <div class="invalid-feedback">
                            {{ form.gender.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.pronouns.id_for_label }}" class="form-label">{{ form.pronouns.label }}</label>
                    <input type="text" class="form-control {% if form.pronouns.errors %}is-invalid{% endif %}"
                           name="{{ form.pronouns.html_name }}" placeholder="{{ form.pronouns.label }}">
                    {% if form.pronouns.errors %}
                        <div class="invalid-feedback">
                            {{ form.pronouns.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.phone_number.id_for_label }}"
                           class="form-label">{{ form.phone_number.label }}</label>
                    <input type="text" class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                           name="{{ form.phone_number.html_name }}" placeholder="{{ form.phone_number.label }}"
                           required>
                    {% if form.phone_number.errors %}
                        <div class="invalid-feedback">
                            {{ form.phone_number.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.street_address.id_for_label }}"
                           class="form-label">{{ form.street_address.label }}</label>
                    <input type="text" class="form-control {% if form.street_address.errors %}is-invalid{% endif %}"
                           name="{{ form.street_address.html_name }}" placeholder="{{ form.street_address.label }}"
                           required>
                    {% if form.street_adress.errors %}
                        <div class="invalid-feedback">
                            {{ form.street_adress.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.postcode.id_for_label }}" class="form-label">{{ form.postcode.label }}</label>
                    <input type="text" class="form-control {% if form.postcode.errors %}is-invalid{% endif %}"
                           name="{{ form.postcode.html_name }}" placeholder="{{ form.postcode.label }}" required>
                    {% if form.postcode.errors %}
                        <div class="invalid-feedback">
                            {{ form.postcode.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.city.id_for_label }}" class="form-label">{{ form.city.label }}</label>
                    <input type="text" class="form-control {% if form.city.errors %}is-invalid{% endif %}"
                           name="{{ form.city.html_name }}" placeholder="{{ form.city.label }}" required>
                    {% if form.city.errors %}
                        <div class="invalid-feedback">
                            {{ form.city.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg">
                <div class="form-group reg_spacing">
                    <label for="{{ form.student_type.id_for_label }}"
                           class="form-label">{{ form.student_type.label }}</label>
                    <select class="form-select custom-select {% if form.student_type.errors %}is-invalid{% endif %}"
                            name="{{ form.student_type.html_name }}" id="gender" required>
                        {% for choice in form.student_type %}
                            {{ choice }}
                        {% endfor %}
                    </select>
                    {% if form.student_type.errors %}
                        <div class="invalid-feedback">
                            {{ form.student_type.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing"> {% bootstrap_field form.sports_card_number  %}                 
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.preferred_language.id_for_label }}"
                           class="form-label">{{ form.preferred_language.label }}</label>
                    <select class="form-select custom-select {% if form.preferred_language.errors %}is-invalid{% endif %}"
                            name="{{ form.preferred_language.html_name }}" id="gender" required>
                        {% for choice in form.preferred_language %}
                            {{ choice }}
                        {% endfor %}
                    </select>
                    {% if form.preferred_language.errors %}
                        <div class="invalid-feedback">
                            {{ form.preferred_language.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.other_club.id_for_label }}"
                           class="form-label">{% trans "Are you currently part of another frisbee association?" %}</label>
                    <br>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input {% if form.other_club.errors %}is-invalid{% endif %}"
                               type="radio" name="{{ form.other_club.html_name }}" value="on">
                        <label class="form-check-label">{% trans "yes" %}</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input {% if form.other_club.errors %}is-invalid{% endif %}"
                               type="radio" name="{{ form.other_club.html_name }}" value="off" checked>
                        <label class="form-check-label">{% trans "no" %}</label>
                    </div>
                    {% if form.other_club.errors %}
                        <div class="invalid-feedback">
                            {{ form.other_club.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}</label>
                    <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                           name="{{ form.email.html_name }}" placeholder="{{ form.email.label }}" required>
                    {% if form.email.errors %}
                        <div class="invalid-feedback">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-group reg_spacing">
                    {% bootstrap_field form.google_email placeholder="...@gmail.com" %}
                </div>
                <div class="form-group reg_spacing">
                    {% bootstrap_field form.password %}
                </div>

            </div>

            <div class="form-group reg_spacing">
                <div>
                    <label>{% trans "By checking the box below, you agree to the " %}
                        <a href="{{ privacyFile.url }}" target="_blank"> {% trans "privacy statement" %}</a>
                        .</label>
                </div>
                <input class="form-check-input {% if form.data_registration.errors %}is-invalid{% endif %}"
                       type="checkbox" id="flexCheckDefault" name="{{ form.data_registration.html_name }}" required>
                <label class="form-check-label"
                       for="{{ form.data_registration.id_for_label }}">{% trans "I agree with the privacy statement" %}</label>
                {% if form.data_registration.errors %}
                    <div class="invalid-feedback">
                        {{ form.data_registration.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group reg_spacing">
                <div class="mb-3">
                    <label class="form-label" for="{{ form.remarks.id_for_label }}">{{ form.remarks.label }}</label>
                    <textarea name="{{ form.remarks.html_name }}" cols="10" rows="3"
                              class="form-control {% if form.remarks.errors %}is-invalid{% endif %}" title=""
                              id="{{ form.remarks.id_for_label }}"></textarea>
                </div>
                {% if form.remarks.errors %}
                    <div class="invalid-feedback">
                        {{ form.remarks.errors }}
                    </div>
                {% endif %}
            </div>
        </div>


        <center><h1>
            <input type="submit" value="{% trans "Become a member" %}!" class="btn btn-primary reg_btn">
        </h1></center>
    </form>

{% endblock content %}

website/members/templates/members/member_detail.html
{% extends "page.html" %}
{% load i18n static cms_tags events_datetimerange thumbnail %}

{% block title %}{{ object.name }}{% endblock title %}
{% block pagetitle %}{{ object.name }}{% endblock pagetitle %}
{% block pagesubtitle %}{{ object.default_pronouns }}{% endblock pagesubtitle %}

{% block content %}

    <div class="row mb-3">
        <div class="col-6">
            {% if object.profile_picture %}
            <div class="w-100 d-flex justify-content-center px-0">
                <img src="{{ object.profile_picture.url }}" class="img-fluid"
                     alt="{% trans 'image for' %} {{ object.name }}">
            </div>
            {% endif %}
        </div>
        <div class="col-6">
            <div class="row mb-3">
                <h6>{% trans "Committees" %}</h6>
                <ul class="list-group pe-0">
                    {% for membership in committee_memberships %}
                        {% if membership.committee.show_in_achievements %}
                            <li class="list-group-item {% if membership.until is None %}active{% endif %}">
                                <b>{{ membership.committee.name }}</b>{% if membership.chair %} <i class="fa-solid fa-chair"></i>{% endif %}
                                <small class="fst-italic ps-2"> {{ membership.since }}
                                {% if membership.until %}- {{ membership.until }}{% endif %}</small>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% if board_memberships %}
                <div class="row mb-3">
                    <h6>{% trans "Boards" %}</h6>
                    <ul class="list-group pe-0">
                        {% for membership in board_memberships %}
                            <li class="list-group-item {% if membership.board.is_current_board %}active{% endif %}">
                                <b>{{ membership.function }} {% trans "of the board of" %} {{ membership.board.start.year }}-{{ membership.board.end.year }}</b>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if object.bio %}
                <div class="row mb-3 p-3 bg-secondary rounded">
                    <p class="m-0">
                        {{ object.bio }}
                    </p>
                </div>
            {% endif %}
            {% if object.user == request.user %}
                <div class="row mb-3">
                    <a class="btn btn-outline-primary" href="{% url "members:edit" %}">{% trans "Edit profile" %}</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

website/members/templates/members/member_form.html
{% extends "page.html" %}
{% load i18n bootstrap5 static %}

{% block title %}{{ object.name }}{% endblock title %}
{% block pagetitle %}{{ object.name }}{% endblock pagetitle %}

{% block extrajs %}
    <script src="{% static 'members/js/cropper.min.js' %}"></script>
    <script src="{% static 'members/js/edit-profile.js' %}"></script>
{% endblock extrajs %}

{% block extracss %}
    <link rel="stylesheet" href="{% static 'members/js/cropper.min.css' %}">
{% endblock extracss %}

{% block content %}
    <form action="{% url "members:edit" %}" enctype="multipart/form-data" method="post" class="form">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="row mb-3">
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="row g-5">
            <div class="col-12 col-lg-6 mb-3">
                <div class="w-100 d-flex justify-content-center px-0 mb-2">
                    <img id="profile_image" src="{% if form.profile_picture.value %}{{ form.profile_picture.value.url }}{% else %}data:image/svg+xml;base64,PHN2ZyBjbGFzcz0iaW1nLWZsdWlkIGZpbGwtcHJpbWFyeSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgNDQ4IDUxMiI+PCEtLSEgRm9udCBBd2Vzb21lIFBybyA2LjIuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZSAoQ29tbWVyY2lhbCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMiBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTIyNCAyNTZjNzAuNyAwIDEyOC01Ny4zIDEyOC0xMjhTMjk0LjcgMCAyMjQgMFM5NiA1Ny4zIDk2IDEyOHM1Ny4zIDEyOCAxMjggMTI4em0tNDUuNyA0OEM3OS44IDMwNCAwIDM4My44IDAgNDgyLjNDMCA0OTguNyAxMy4zIDUxMiAyOS43IDUxMkg0MTguM2MxNi40IDAgMjkuNy0xMy4zIDI5LjctMjkuN0M0NDggMzgzLjggMzY4LjIgMzA0IDI2OS43IDMwNEgxNzguM3oiLz48L3N2Zz4K{% endif %}" class="img-fluid">
                </div>
                <div class="input-group">
                    {% if form.profile_picture.value %}
                    <div class="input-group-text">
                        <label for="profile_picture-clear_id" class="me-2">Clear</label>
                        <input class="form-check-input mt-0" type="checkbox" name="profile_picture-clear" id="profile_picture-clear_id">
                    </div>
                    {% endif %}
                    <input type="file" name="profile_picture" accept="image/*" class="form-control" title="" id="id_profile_picture">
                </div>
            </div>
            <div class="col-12 col-lg-6 mb-3">
                {% bootstrap_form form form_group_class="row mb-4" label_class="fw-bold mb-3" field_class="ms-3" exclude="profile_picture,bio" %}

                <div class="row mb-4">
                    <label class="fw-bold mb-3" for="{{ form.bio.id_for_label }}">{{ form.bio.label }}</label>
                    <div class="ms-3">
                        <textarea name="{{ form.bio.html_name }}" cols="40" rows="3" maxlength="{{ field.field.max_length }}" class="form-control px-4 py-3" placeholder="{{ form.bio.label }}" id="{{ form.bio.id_for_label }}" spellcheck="true">{{ form.bio.value }}</textarea>
                    </div>
                </div>
            </div>
        </div>

        <center>{% bootstrap_button button_type="submit" content="Save" %}</center>
    </form>
{% endblock content %}