website/events/urls.py
from django.urls import path

from events.views import (
    EventListView,
    EventDetailView,
    EventRegisterView,
    EventUnregisterView,
    EventFormView,
    EventICSView,
)

urlpatterns = [
    path("", EventListView.as_view(), name="list"),
    path("events.ics", EventICSView.as_view(), name="ics"),
    path("<int:pk>/", EventDetailView.as_view(), name="detail"),
    path("<int:pk>/register/", EventRegisterView.as_view(), name="register"),
    path("<int:pk>/form", EventFormView.as_view(), name="form"),
    path("<int:pk>/unregister/", EventUnregisterView.as_view(), name="unregister"),
]

website/website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from cms.sitemaps import CMSSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.defaults import page_not_found, server_error

from members.sitemaps import BecomeAMemberSitemap
from members.views import BecomeAMemberView, PasswordSetView


def custom_page_not_found(request):
    return page_not_found(request, None)


def custom_server_error(request):
    return server_error(request)


urlpatterns = (
    [
        path("i18n/", include("django.conf.urls.i18n")),
        path(
            "sitemap.xml",
            sitemap,
            {"sitemaps": {"cmspages": CMSSitemap, "member": BecomeAMemberSitemap}},
        ),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

urlpatterns += i18n_patterns(
    path("404/", custom_page_not_found),
    path("500/", custom_server_error),
    path("admin/", admin.site.urls),
    path("user/", include("django.contrib.auth.urls")),
    path("become-a-member/", BecomeAMemberView.as_view(), name="become-a-member"),
    path(
        "activate-account/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="activate-account",
    ),
    re_path(r"^", include("cms.urls")),
)

website/boards/models.py
import datetime

from cms.models.pluginmodel import CMSPlugin
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import SET_NULL
from django.utils.translation import gettext_lazy as _
from filer.fields.image import FilerImageField

from members.models import Member
from utils.translations import ModelTranslateMeta, MultilingualField


class Board(models.Model):
    start = models.DateField(verbose_name=_("start"))
    end = models.DateField(verbose_name=_("end"))
    picture = FilerImageField(
        blank=True, null=True, on_delete=SET_NULL, verbose_name=_("picture")
    )

    @property
    def is_current_board(self):
        return self.start <= datetime.date.today() < self.end

    def clean(self):
        if self.end and self.start > self.end:
            raise ValidationError({"start": _("Start date should be before end date.")})
        else:
            for board in Board.objects.all():
                if board is self or board.end is None:
                    continue
                if board.start < self.start < board.end:
                    raise ValidationError(
                        {"start": _("A boards start cannot fall in another board")}
                    )

    def validate_unique(self, **kwargs):
        super().validate_unique(**kwargs)
        for board in Board.objects.all():
            if board == self:
                continue
            if (
                board.end
                and (
                    self.start < board.end <= self.end
                    or board.start <= self.start < board.end
                    or board.start < self.end <= board.end
                )
                or self.start <= board.start < self.end
            ):
                raise ValidationError(
                    {
                        "start": _(
                            "A boards start and end cannot overlap with another board"
                        ),
                        "end": _(
                            "A boards start and end cannot overlap with another board"
                        ),
                    }
                )

    def __str__(self):
        return _("Board of") + " " + str(self.start.year)


class BoardMembership(models.Model, metaclass=ModelTranslateMeta):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, verbose_name=_("board"))

    member = models.ForeignKey(
        Member,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name=_("member"),
    )
    name = models.CharField(
        max_length=255, blank=True, null=True, verbose_name=_("name")
    )
    function = MultilingualField(
        models.CharField, max_length=255, verbose_name=_("function")
    )
    email = models.EmailField(verbose_name=_("email"))
    description = models.TextField(blank=True, null=True, verbose_name=_("description"))
    picture = FilerImageField(
        blank=True, null=True, on_delete=SET_NULL, verbose_name=_("picture")
    )

    def clean(self):
        if self.member is not None and self.name is not None:
            raise ValidationError(
                {
                    "member": _("Either member or name have to be filled in, not both"),
                    "name": _("Either member or name have to be filled in, not both"),
                }
            )

        if self.member is None and self.name is None:
            raise ValidationError(
                {
                    "member": _("Either member or name is required"),
                    "name": _("Either member or name is required"),
                }
            )

    def __str__(self):
        return (
            "boardmembership: "
            + (self.name if self.name else self.member.name())
            + " "
            + str(self.board.start.year)
            + "/"
            + str(self.board.end.year)
        )


class PreviousBoardModel(CMSPlugin):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

website/boards/templates/current_board_plugin.html
{% load i18n %}
<div class="row">
    {% for board in boards %}
        {% with current=forloop.first %}
            <div class="col-lg-{% if board.picture %}12{% else %}6{% endif %} row">
                <div class="col-lg-{% if board.picture %}6{% else %}12{% endif %} mb-3">
                    <h3>{% trans "Board of" %} {{ board.start.year }}-{{ board.end.year }}</h3>
                    <ul class="list-group list-group-flush">
                        {% for board_member in board.boardmembership_set.all|dictsort:"id" %}
                            {% if board_member.picture or board_member.description %}
                                <button type="button" role="button" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" data-bs-toggle="modal" data-bs-target="#y{{ year }}m{{ board_member.id }}">
                                    <p class="mb-0 me-2 text-body">
                                        {{ board_member.function }}:
                                        {% if board_member.member %}{{ board_member.member.user.get_full_name }}{% else %}{{ board_member.name }}{% endif %}
                                        {% if current %}(<a href="mailto:{{ board_member.email }}">{{ board_member.email }}</a>){% endif %}
                                    </p>
                                    <span class="badge bg-primary rounded-pill"> > </span>
                                </button>
                                <div class="modal fade" id="y{{ year }}m{{ board_member.id }}" tabindex="-1" aria-labelledby="y{{ year }}m{{ board_member.id }}label" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="y{{ year }}m{{ board_member.id }}label">
                                                    {{ board_member.function }}: {% if board_member.member %}{{ board_member.member.user.first_name }}{% else %}{{ board_member.name }}{% endif %}
                                                </h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                {% if board_member.picture %}<img class="img-fluid mb-3" src="{{ board_member.picture.url }}" />{% endif %}
                                                {% if board_member.description %}<p>{{ board_member.description }}</p>{% endif %}
                                                <p>
                                                    <a href="mailto:{{ board_member.email }}">{{ board_member.email }}</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="list-group-item">
                                    <p class="mb-0">
                                        {{ board_member.function }}:
                                        {% if board_member.member %}{{ board_member.member.user.get_full_name }}{% else %}{{ board_member.name }}{% endif %}
                                        {% if current %}(<a href="mailto:{{ board_member.email }}">{{ board_member.email }}</a>){% endif %}
                                    </p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-6 mb-3">
                    {% if board.picture %}<img class="img-fluid" src="{{ board.picture.url }}"/>{% endif %}
                </div>
            </div>
        {% endwith %}
    {% endfor %}
</div>